name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Unit Tests
      run: make test-unit
    - name: Lint
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        make lint
    - name: Tidy
      run: make go-mod-tidy
    - name: Test Build
      run: make build
    - name: Run GoReleaser Test
      uses: goreleaser/goreleaser-action@v3
      with:
        args: release --snapshot --skip=publish --clean
